export const ALL_DESIGNER_REQUEST = "ALL_DESIGNER_REQUEST";
export const ALL_DESIGNER_SUCCESS = "ALL_DESIGNER_SUCCESS";
export const ALL_DESIGNER_FAIL = "ALL_DESIGNER_FAIL";


export const DESIGNER_DETAILS_REQUEST = "DESIGNER_DETAILS_REQUEST";
export const DESIGNER_DETAILS_SUCCESS = "DESIGNER_DETAILS_SUCCESS";
export const DESIGNER_DETAILS_FAIL = "DESIGNER_DETAILS_FAIL ";


export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const DESIGNER_LOGIN_REQUEST = "DESIGNER_LOGIN_REQUEST";
export const DESIGNER_LOGIN_SUCCESS = "DESIGNER_LOGIN_SUCCESS";
export const DESIGNER_LOGIN_FAIL = "DESIGNER_LOGIN_FAIL";

export const REGISTER_DESIGNER_REQUEST = "REGISTER_DESIGNER_REQUEST";
export const REGISTER_DESIGNER_SUCCESS = "REGISTER_DESIGNER_SUCCESS";
export const REGISTER_DESIGNER_FAIL = "REGISTER_DESIGNER_FAIL";

export const ADMIN_DESIGNER_REQUEST = "ADMIN_DESIGNER_REQUEST";
export const ADMIN_DESIGNER_SUCCESS = "ADMIN_DESIGNER_SUCCESS";
export const ADMIN_DESIGNER_FAIL = "ADMIN_DESIGNER_FAIL";   


export const CLEAR_ERRORS = "CLEAR_ERRORS";